[package]
name = "yu"
version = "0.1.0"
authors = ["Ravern Koh <ravernkoh@gmail.com>"]

[dependencies]
clap = { version = "2.32", default-features = false, features = ["suggestions"] }
failure = "0.1.2"
fern = "0.5.6"
log = "0.4"
