-- This module serves as the root of the `LeanPlayground` library.
-- Import modules here that should be built as part of the library.
import LeanPlayground.E00_Warmups
import LeanPlayground.E01_Propositions
import LeanPlayground.E02_Classical
import LeanPlayground.E03_ClassicalExtra
import LeanPlayground.E04_Quantifiers
import LeanPlayground.E05_Existentials
import LeanPlayground.E06_Specifications
import LeanPlayground.E07_Tactics
import LeanPlayground.E08_NatAndLists
import LeanPlayground.E09_SyntaxTrees
import LeanPlayground.E10_InductiveExtras
import LeanPlayground.E11_TypeClasses
import LeanPlayground.E12_Recursion
import LeanPlayground.E13_ExpressionOptimizer
import LeanPlayground.E14_ListTransformations
import LeanPlayground.E15_Palindromes
import LeanPlayground.E16_Subsequences
import LeanPlayground.E17_BinaryNumbers
import LeanPlayground.E18_Cantor
import LeanPlayground.E19_VerifiedSort
import LeanPlayground.E20_StackCompiler
import LeanPlayground.E21_TypeSafety
